#pragma config(Sensor, dgtl1,  p1,             sensorDigitalOut)
#pragma config(Sensor, dgtl2,  p2,             sensorDigitalOut)
#pragma config(Sensor, dgtl3,  p3,             sensorDigitalOut)
#pragma config(Sensor, dgtl4,  p4,             sensorDigitalOut)
#pragma config(Sensor, dgtl5,  crank1,         sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  crank2,         sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  button1,        sensorTouch)
#pragma config(Sensor, dgtl10, button2,        sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int offset = 0;
int rpm = 0;


task speed()
{
	long lastTime = nSysTime;
	int lastTick = SensorValue(crank1);

	while(true)
	{
		rpm = ((float)(SensorValue(crank1) - lastTick) / 360.0)  / ((float)(nSysTime - lastTime) / 60000.0);
		lastTime = nSysTime;
		lastTick = SensorValue(crank1);
		sleep(50);
	}
}

task display()
{
	bool set = true;
	string out = "";
	bLCDBacklight = true;

	while(true)
	{
		if(set)
		{
			offset += ((nLCDButtons == 4) - (nLCDButtons == 1))*5;
			set = false;
		}
		else if(nLCDButtons == 0)
			set = true;

		if(nLCDButtons == 2)
			SensorValue(crank1) = 0;

		if(SensorValue(button2))
			SensorValue(crank2) = 0;

		//sprintf(out, "RPM: %d", rpm);
		sprintf(out, "%d %d %d %d %d %d",SensorValue(p1),SensorValue(p2),SensorValue(p3),SensorValue(p4),SensorValue(crank1),SensorValue(crank2));
		clearLCDLine(0);
		displayLCDString(0,0,out);

		sprintf(out, "offset: %d", offset);
		clearLCDLine(1);
		displayLCDString(1,0,out);

		sleep(50);
	}
}

task main()
{
	startTask(display);
	//startTask(speed);
	while(true)
	{
		if(SensorValue(crank
		SensorValue(p1) = SensorValue(p2) = (((SensorValue(crank1) + offset) / 180) & 1);
		SensorValue(p3) = SensorValue(p4) = ((SensorValue(crank2) + offset) / 180) & 1;
	}
}
